
# The list of models used
llm_models:
  mini: gpt-5-mini-2025-08-07
  reasoning: gpt-5
  non-reasoning: gpt-5

# ---------------------------------------------------------
# The list of models used for text modifiers
# ---------------------------------------------------------
text_modifier_models:
  copy_editor: 
    model: gpt-4o
    temperature: 0.1
    max_tokens: 8000
    top_p: 1
    frequency_penalty: 0
    presence_penalty: 0
    stop_sequences: []
    timeout: 30

  # ---------------------------------------------------------
  summarizer:
    model: gpt-5  # we need reasoning here
    temperature: 0.0
    max_tokens: 20000  # Increased to handle longer summaries
    timeout: 300

  # ---------------------------------------------------------
  key_achievements:
    model: gpt-5 
    temperature: 0.0
    max_tokens: 20000  # Sufficient for structured JSON output
    timeout: 300

# ---------------------------------------------------------
  review_text_evaluator:
    model: gpt-5 
    temperature: 0.0
    max_tokens: 20000  # Sufficient for structured JSON output
    timeout: 300

# Embeddings are used to convert text and images into vectors 
# that can be used for similarity search.

embeddings:
  multimodal:
    model: "ViT-B-16-SigLIP2"
    size: 768
    distance: "cosine"
  text:
    model: "all-MiniLM-L6-v2"
    size: 384
    distance: "cosine"
  
# Vector DB particulars
vector_db:
  type: "qdrant"
  path: "qdrant_db"
  text_only_basic:
    collection_name: "text_only_basic"
    vector_size: 384
  multimodal_basic:
    collection_name: "multimodal_basic"
    vector_size: 768

paths:
  data: /Users/asifqamar/github/metamorphosis/data
  