site_name: SupportVectors MetaMorphosis
site_description: A simple example with AI Agents
site_author: SupportVectors
site_url: https://supportvectors.ai/metamorphosis

# -----------------------------------------------------------------------------
# Theme configuration
# -----------------------------------------------------------------------------
theme:
  name: material
  logo: images/overlapping_logo.png
  favicon: images/favicon.ico

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: 'light blue'
      accent: 'gray'
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    text: 'Lora'
    code: 'Roboto Mono'
    code_title: 'Roboto Mono'
    code_block: 'Roboto Mono'
    code_font_size: 0.9rem
    heading: 'Merriweather'
    heading_weight: 300
    heading_line_height: 1.5

# -----------------------------------------------------------------------------
# Plugins configuration
# -----------------------------------------------------------------------------

plugins:
  - search
  - mknotebooks:
      # Configure mknotebooks to avoid template deprecation warnings
      enable_default_jupyter_cell_styling: true
      execute: false
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_source: true
  - awesome-pages
  - mermaid2
  - include-markdown:
      comments: false #This stops the include-markdown plugin comments from being displayed

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid

extra_css:
  - stylesheets/supportvectors.css

extra_javascript:
  - javascripts/mathjax.js
  #- https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra:
  PYTHONPATH: src

# -----------------------------------------------------------------------------
# Navigation structure
# -----------------------------------------------------------------------------
nav:
  - Home: index.md
  - Architecture: architecture.md
  - Package Documentation:
    - Overview: metamorphosis/index.md
    - MCP Package:
      - Overview: metamorphosis/mcp/index.md
      - TextModifiers: metamorphosis/mcp/TextModifiers.md
    - Agents Package:
      - Overview: metamorphosis/agents/index.md
    - Core Modules:
      - Data Models: metamorphosis/datamodel.md
      - Exceptions: metamorphosis/exceptions.md
      - Utilities: metamorphosis/utilities.md
      - Model Registry: metamorphosis/model_registry.md
  - Examples:
    - Overview: examples/index.md
    - Basic Processing:
      - Summarizer Usage: examples/summarizer_usage.md
      - Copy Editor Usage: examples/rationalize_usage.md
    - Advanced Processing:
      - Achievement Extraction: examples/extract_achievements_usage.md
      - Quality Evaluation: examples/review_text_evaluator_usage.md
    - Visualization:
      - Radar Charts: examples/visualize_evaluation_radar.md
  - Project Guide:
    - Tips & Tricks:
      - CUDA Issues: project-guide/tips-and-tricks/cuda-hell.md
  - Notebooks:
    - Common Patterns: notebooks/supportvectors-common.ipynb

